/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-auto-img
export {}

declare module 'virtual:images' {
  export interface ImageMap {
    'IHello': string
  }
}

declare module 'vue' {
  interface ComponentCustomProperties {
    readonly 'IHello': typeof import('/src/assets/images/hello.png')['default']
  }
}
